GET https://640f55c04ed25579dc4c7a34.mockapi.io/employees

###

GET https://640f55c04ed25579dc4c7a34.mockapi.io/employees/4

###
POST https://640f55c04ed25579dc4c7a34.mockapi.io/employees
content-type: application/json

{
    "name": "sample122",
    "time": "Wed, 21 Oct 2015 18:27:50 GMT"
}

###
PATCH https://640f55c04ed25579dc4c7a34.mockapi.io/employees/4
Content-Type: application/json

{
  "name": "JANEY"
}

###
PUT https://640f55c04ed25579dc4c7a34.mockapi.io/employees/123
content-type: application/json

{
    "name": "sample1",
    "salary": 65000
}

###
DELETE https://640f55c04ed25579dc4c7a34.mockapi.io/employees/123